const User = require('../models/user');
const SchoolAdmin = require('../models/school_admin');
const { generateRandomPassword } = require('../middleware/auth');
const { sendActivationEmail } = require('../../config/mail');
const School = require('../models/school');

const createNewAdmin = async (req, res) => {
    const { email, firstName, lastName, role, schoolId } = req.body;
    const autogeneratedPassword = generateRandomPassword();

    try {
        const adminSchool = await School.findOne({
            where: {
                school_id: schoolId
            }
        });
        if (!adminSchool) {
            return res.status(400).json({
                message: `Cannot create admin if the school does not exist`,
                data: {
                    ...req.body
                }
            });
        }

        const newUser = await User.create({
            email: email.toLowerCase(),
            password: autogeneratedPassword,
            user_type: "school_admin"
        });
        if (newUser) {
            const newAdmin = await SchoolAdmin.create({
                first_name: firstName,
                last_name: lastName,
                role,
                admin_id: newUser.dataValues.id,
                school_id: schoolId
            });
            if (newAdmin) {
                let token = await newAdmin.generateToken();
                let mailOptions = {
                    userType: newUser.user_type === "staff" ? "staff" : "school administrator",
                    activationLink: `${process.env.BASE_FRONTEND_URL}/verify/${token}`,
                    email,
                    password: autogeneratedPassword,
                    schoolName: adminSchool.name
                };
                if (token) {
                    await sendActivationEmail(mailOptions);
                    return res.status(200).json({
                        message: "School admin created successfully & email sent",
                        data: {
                            ...newAdmin.dataValues,
                            activationLink: mailOptions.activationLink
                        },
                    });
                }
            }
        }
    } catch (error) {
        return res.status(500).json({ message: error });
    }
};

// const sendMail = async (req, res) => {
//     try {
//         console.log(`${process.env.BASE_FRONTEND_URL}/verify/qwweeee`);
//         let mailOptions = {
//             userType: "asdd",
//             activationLink: `${process.env.BASE_FRONTEND_URL}/verify/qwweeee`,
//             email: "khairahscorner@gmail.com",
//             password: "autogeneratedPassword",
//             schoolName: "adminSchool.name"
//         };
//         sendActivationEmail(mailOptions);
//         return res.status(200).json({
//             message: "success",
//         });

//     } catch (error) {
//         return res.status(500).send({ message: error });
//     }
// };

module.exports = { createNewAdmin };